PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
# PATH="/home/john/.local/bin:~/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH"
PATH="$PATH:~/.local/bin"
# PATH="$PATH:/Users/john/Library/Python/3.8/bin"
PATH="$PATH:/Users/john/Library/Python/3.9/bin"
