install:
	./build
	ln -sf $$(find ~/dotfiles/.xmonad/.stack-work/install -name xmonad-local-exe) ~/dotfiles/.xmonad/xmonad-x86_64-linux
	ln -sf ~/dotfiles/.xmonad/xmonad-x86_64-linux ~/.local/bin/xmonad
