# git clone https://github.com/alacritty/alacritty-theme.git ~/.config/alacritty/themes
# curl https://raw.githubusercontent.com/josean-dev/dev-environment-files/main/.config/alacritty/themes/themes/coolnight.toml --output ~/.config/alacritty/themes/themes/coolnight.toml
import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

opacity = 0.75
blur = true


option_as_alt = "OnlyLeft"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font]
size = 22

